web:
  image: iojs:2.0.0
  command: npm start
  working_dir: /usr/src/app
  volumes:
    - .:/usr/src/app
  ports:
    - 0.0.0.0:3000:3000
    - 127.0.0.1:5858:5858
    - 127.0.0.1:5859:5859
  tty: true
  stdin_open: true
  environment:
    WDIO_HOSTNAME: machine.dev
